sudo: required

services:
  - docker

before_install:
  - docker build -t mallamty/working-with-docker -f Dockerfile.dev .

script:
   - docker run -e CI=true mallamty/working-with-docker npm run test

